name: Java Build and Release

on:
  push:
    branches:
      - main

env:
  MAVEN_OPTS: "-Dmaven.repo.local=$HOME/.m2/repository"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        architecture: x64

    - name: Build with Maven
      run: mvn package

    - name: Upload artifact to GitHub Releases
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ env.upload_url }}
        asset_path: target/ShareIdea-1.0-SNAPSHOT.jar
        asset_name: ShareIdea-1.0-SNAPSHOT.jar
        asset_content_type: application/java-archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
