name: Build and Release
on:
  push:
    branches:
      - main
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn package
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
          GITHUB_TOKEN: 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
      with:
          tag_name: v1.0
          release_name: Release 1.0
          body: |
            This Is The First Release
          draft: false
          prerelease: false
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
          name: ShareIdea
          path: target/ShareIdea.jar
