name: Build Minecraft Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
      
    - name: Build with Maven
      run: mvn package

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ShareIdea
        path: target/ShareIdea.jar
