name: Java Build and Upload Artifact

on:
  push:
    branches:
      - main

env:
  MAVEN_OPTS: "-Dmaven.repo.local=$HOME/.m2/repository"

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        architecture: x64
        java-package: jdk
        distribution: adopt
        
    - name: Build with Maven
      run: mvn package

    - name: Upload artifact to main branch
      uses: actions/upload-artifact@v2
      with:
        name: ShareIdea
        path: target/ShareIdea-1.0-SNAPSHOT.jar
        target-path: ShareIdea-1.0-SNAPSHOT.jar
